### ISSUE TITLE
Missing 1.0.1 on packagist

### ISSUE THREAD

**Issue by jmleroux** [bruceheller/images-generator#3]
Hello,

The tag 1.0.1 is not on packagist : https://packagist.org/packages/bheller/images-generator

Is it normal ?

Regards,
JM

**Comment by bruceheller** [comment]
Hello,

Not at all, but I know why, I forgot to update the release number in the composer.json file.

I'm doing it right away.

Thanks.

**Comment by bruceheller** [comment]
Should be good now, sorry again.

**Comment by jmleroux** [comment]
Thank you for the reactivity :+1:
